### ISSUE TITLE
Protocol Ecto.Queryable not implemented for %Composite{}

### ISSUE THREAD

**Issue by dfnino10** [fuelen/composite#6]
Getting a strange behavior where the query created with Composite will fail randomly with the error

`** (Protocol.UndefinedError) protocol Ecto.Queryable not implemented for %Composite{...}`

This does not happen always, but instead randomly without any change in the code. Perhaps the apply function is not being applied automatically?

My query is created as follows:

```
    Schema
    |> Composite.new(params)
    |> Composite.param([:param1], &filter_by_param1/2)
    |> Composite.param([:param2], &filter_by_param2/2, requires: :schema2)
    |> Composite.dependency(:plan, &join_schema2/1)
    |> Repo.all()
```

To reiterate, this is working in some cases and some cases is not. There isn't any change between successful and unsuccessful runs. 

I'm using composite 0.4.3.

**Comment by fuelen** [comment]
Hi @dfnino10 

This protocol is implemented only if ecto is available
https://github.com/fuelen/composite/blob/47916721d5f1468eccdcaf6ee48167cb3c4dc308/lib/composite.ex#L390

Ensure that ecto is added explicitly to the list of dependencies.
Even if ecto is present, you may experience this issue if the dependency was compiled before the ecto was added to the project. In this case, just force recompile the composite dependency.

**Comment by fuelen** [comment]
Hey @dfnino10
Does it solve the issue?

**Comment by dfnino10** [comment]
Thank you for your answer @fuelen. This is likely the solution to the issue I was having. The workaround I did at that time was to call `Composite.apply()` before `Repo.all()`.
